name: Validate PR on develop branch

on:
    push:
      branches:
        - main
    pull_request:
      types: [opened, synchronize]
      branches: [ develop ]
      paths-ignore:
            - 'README.md'
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    checkout-build-deploy:
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read
      steps:
        - name: 'Checkout Repo'
          uses: actions/checkout@v2.3.2
        
        - name: Log in to the Container registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
          
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
        - name: Build and push to Docker
          uses: docker/build-push-action@v2
          with:
            ontext: .
            file: ./Dockerfile
            push: true
            images: ghcr.io/${{ github.repository }}
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}